1.15 - RECUPERAR SENHA.
NewSchoolApp/newschool-frontend pull request #113
Opened 2020-01-13 02:13 UTC by cidcair

- Nessa tarefa foi entregue a pagina de recuperar a senha.

2020-01-13 02:19 UTC, dcaueb78 approved these changes

2020-01-13 02:29 UTC, andrews-felipe approved these changes
Ótimo, apenas algumas considerações básicas.

Commits: sempre aconselhável colocar o que está sendo alterado ou implementado, 
pois na hora do merge, esses commits vão se unir com o histórico, então fica registrado pra sempre, então ai tem `mensagem`, `msg`, `agora é gol`, eu não sei o que você modificou ai certo?

2020-01-13 02:29 UTC, andrews-felipe commented on pages/public/forgotpassword.vue
> +@import url("https://fonts.googleapis.com/css?family=Montserrat:400,500,900&display=swap");
acho que pode remover isso tbm, alguns componentes estão com isso, inclusive uns aqui, se tiver já como remover, pois ja definimos nas configurações do nuxt um type padrão que é a `montserrat`

2020-01-13 02:29 UTC, andrews-felipe commented on pages/public/signup.vue
>  </style>
São não esquecer de pôr o `scoped `todas as vezes que um componente novo for criado
`<style scoped> ...`

2020-01-14 05:24 UTC, andrews-felipe approved these changes

2020-01-14 05:24 UTC, andrews-felipe commented on services/http/courses.js
> +    return http.get('/api/v1/course', {
Depois precisamos migrar tudo pra o generics

2020-01-14 14:08 UTC, filipefelice submitted a review, later dismissed
👏🏻👏🏻👌🏻

2020-01-14 14:09 UTC, wantero requested changes
Foi feito o merge com a develop antes de subir a PR?

2020-01-14 14:09 UTC, wantero commented on components/ShareBtn.vue
> +        :url="url"
Essas alterações no ShareBtn fazem parte desta estória?

2020-01-14 14:09 UTC, wantero commented on pages/admin/courses/new.vue
> +<template>
New Course não deveria fazer parte do card de recuperar senha. Porque esse arquivo foi criado nesta PR ?

2020-01-14 14:09 UTC, wantero commented on pages/public/404.vue
> +       <v-btn
essas alterações já foram mergeadas em outra PR.

2020-01-14 14:39 UTC, closed without merging

2020-01-14 14:40 UTC, ericguim commented
> Foi feito o merge com a develop antes de subir a PR?

o merge foi feito errado, estamos publicando uma nova PR