1.07.01 - ADMIN - CRUD AULAS
NewSchoolApp/newschool-frontend pull request #129
Opened 2020-01-15 18:37 UTC by ViniciusDalmazzo

- Criado tela para adicionar uma aula a um curso;
- Criado tela para editar uma aula já existente;
- Implementado comunicação com back-end para adicionar e atualizar aulas através do endpoint **/Lesson**.

[Cartão do trello](https://trello.com/c/ZAdLcwFu).

2020-01-15 23:25 UTC, andrews-felipe requested changes
Somente modificar as chamadas do lesson pra o genérics

2020-01-16 00:37 UTC, ViniciusDalmazzo commented
> Somente modificar as chamadas do lesson pra o genérics

2020-01-16 03:55 UTC, filipefelice approved these changes
Valeu Vini! 👍👏👌

2020-01-16 04:31 UTC, oliveirabalsa approved these changes

2020-01-16 14:38 UTC, andrews-felipe approved these changes

2020-01-16 14:38 UTC, merged