Correções dos botões das redes sociais
NewSchoolApp/newschool-frontend pull request #138
Opened 2020-01-16 21:17 UTC by Luan-max

A organização dos botões ficaram conforme o padrão do figma.

2020-01-16 23:34 UTC, oliveirabalsa commented on components/ShareBtn.vue
> +    SocialSharing,
não seria necessária essa virgula

2020-01-16 23:35 UTC, oliveirabalsa commented on components/ShareBtn.vue
> +      default: '#CCC',
nem essa

2020-01-16 23:35 UTC, oliveirabalsa commented on components/ShareBtn.vue
> +      default: 'MissaoNewSchoolApp',
nem essa

2020-01-16 23:41 UTC, oliveirabalsa commented on components/ShareBtn.vue
> +      default: 'NewSchoolApp',
Só não entendi essas virgulas mas blz hahah

2020-01-16 23:41 UTC, oliveirabalsa approved these changes

2020-01-17 00:15 UTC, filipefelice requested changes
Por gentileza retirar as virgulas

2020-01-17 00:35 UTC, pethersonmoreno commented on components/ShareBtn.vue
> +    SocialSharing,
Apesar da vírgula não ser necessária, ela possibilita que futuras edições como adicionar o uso de um novo componente não demonstre alterações em duas linhas, mas apenas na linha adicionado.
Isso tem como configurar no Eslint e no Prettier

2020-01-17 00:35 UTC, pethersonmoreno commented on components/ShareBtn.vue
> +      default: '#CCC',
Pode deixar a vírgula

2020-01-17 00:36 UTC, pethersonmoreno commented on components/ShareBtn.vue
> +      default: 'MissaoNewSchoolApp',
Pode deixar a vírgula

2020-01-17 00:36 UTC, pethersonmoreno commented on components/ShareBtn.vue
> +      default: 'NewSchoolApp',
Pode deixar a vírgula

2020-01-17 00:38 UTC, pethersonmoreno reviewed
> Por gentileza retirar as virgulas

Se remove essas vírgulas prejudica o histórico das alterações, isso inclusive foi discutido em um grande evento em São Paulo, é melhor manter a vírgula nesses casos para futuras edições não parecer que alterou uma linha que não precisava.

Isso pode ser configurado no Eslint e no Prettier

2020-01-17 00:39 UTC, Luan-max commented
deixa a virgula ou não ?

2020-01-17 00:51 UTC, filipefelice approved these changes

2020-01-17 00:53 UTC, pethersonmoreno approved these changes

2020-01-17 02:46 UTC, merged