1.15.2 - recuperar senha
NewSchoolApp/newschool-frontend pull request #148
Opened 2020-01-19 05:31 UTC by cidcair

- Essa é a segunda tela da pagina de recuperar a senha
- Criei a pagina reset_password.vue e modifiquei o nuxt.config.js, auth.js e forgotpassword.vue

2020-01-19 09:36 UTC, wantero requested changes
@cidcair poderia ter mais cuidados com as descrição dos commit? 
Tem vários commit com descrição "gol" e "atualização", mas não explica no commit o que foi alterado.
Os commits servem como histórico das alterações, então uma breve descrição do que foi feito é muito importante para que as pessoas saibam o que foi realizado em cada commit.

2020-01-19 09:36 UTC, wantero commented on nuxt.config.js
> +      'http://back-dev-new-branch-tnlvh2xtya.herokuapp.com/',
@cidcair pq foi alterado o valor desta variável de ambiente do ambiente de dev para o de uma pr?

2020-01-19 09:36 UTC, wantero commented on pages/public/forgotpassword.vue
> +            this.confirmSnackbar('Email invalido.', 'error')
faltou a acentuação no inválido.

2020-01-19 09:36 UTC, wantero commented on pages/student/certificates.vue
> +<<<<<<< HEAD
pq tem comentário de head de merge?

2020-01-19 09:36 UTC, wantero commented on services/http/users.js
> +//     }
porque todos esses métodos foram comentados?

2020-01-19 12:43 UTC, cidcair commented on services/http/users.js
> +//     }
O Andrews havia pedido para que pudesse testar e acabei esquecendo de retirar o comentario

2020-01-19 12:43 UTC, cidcair commented on pages/public/forgotpassword.vue
> +            this.confirmSnackbar('Email invalido.', 'error')
Irei corrigir

2020-01-19 12:46 UTC, cidcair commented on nuxt.config.js
> +      'http://back-dev-new-branch-tnlvh2xtya.herokuapp.com/',
Ocorreu a mudança para o erro que estava ocorrendo pudesse ser visto, pois ele so estava mostrando ele no caminho do backend e acabei esquecendo de mudar de volta para a base_url correta.

2020-01-19 18:19 UTC, andrews-felipe commented on services/http/users.js
> +//     }
esse aquivo deve ser excluído, pois o genérics vai ficar responsável por tudo

2020-01-19 23:26 UTC, wantero approved these changes

2020-01-19 23:50 UTC, ericguim commented on pages/public/forgotpassword.vue
> +/* Global */
Ficou com 2 Global?

2020-01-20 00:32 UTC, ericguim approved these changes

2020-01-20 00:33 UTC, merged