Criando pagina de certificado
NewSchoolApp/newschool-frontend pull request #157
Opened 2020-01-20 20:47 UTC by thi777

#### Essa PR aguarda endpoint do backend e background oficial da equipe de designer

Pode mergear para o Filipe testar o fluxo do app.

- Aguardando endpoint do backend
- Aguardado background oficial do time de Designer
- Resolvendo bug de scroll lateral apontado pelo QA.

Deixei alguns códigos comentados que setam as variáveis que viram do backend, conforme json enviado pelo Eric.

2020-01-21 01:00 UTC, filipefelice requested changes
Boa. Deixa só a rota do certificado pública e corrige botão de compartilhamento.
O @ericguim já vai liberar o serviço pra voce integrar com sua PR.

2020-01-22 14:00 UTC, andrews-felipe commented
tem algum conflito ai.

2020-01-22 14:04 UTC, andrews-felipe requested changes
Só ajustar os conflitos..

2020-01-22 14:41 UTC, thi777 commented
> Boa. Deixa apenas uma rota do certificado público e o botão de compartilhamento.
> O @ericguim já vai liberar o serviço para você integrar com sua PR.

2020-01-22 14:43 UTC, thii777 commented
@filipefelice @andrews-felipe estou com um problema no cursor: pointer mas a noite eu arrumo blz?

2020-01-22 14:48 UTC, oliveirabalsa approved these changes

2020-01-22 14:57 UTC, oliveirabalsa reviewed
Só ajustar, max-width, centralizando o conteúdo e os botões

2020-01-22 15:56 UTC, filipefelice approved these changes

2020-01-22 15:56 UTC, merged