Componente ChartCard
NewSchoolApp/newschool-frontend pull request #267
Opened 2020-09-22 00:25 UTC by HenrryEsposito

Implementação do componente (card) que exibe o componente de PieChart. 
Esse card se encarrega de exibir o gráfico e os labels do mesmo de forma totalmente dinâmica.
Algumas correções na responsividade do componente de gráfico também foram implementadas.

2020-09-22 00:46 UTC, filipefelice requested changes

2020-09-22 00:46 UTC, filipefelice commented on components/ChartCard.vue
> +  <div class="chardCard">
O nome desta classe esta correto? chardCard? não seria chartCard?

2020-09-22 00:46 UTC, filipefelice commented on components/ChartCard.vue
> +.chardCard{
O nome desta classe esta correto? chardCard? não seria chartCard?

2020-09-22 02:59 UTC, HenrryEsposito commented on components/ChartCard.vue
> +  <div class="chardCard">
Corrigido!

2020-09-22 02:59 UTC, HenrryEsposito commented on components/ChartCard.vue
> +.chardCard{
Corrigido, obrigado por verificar!

2020-09-22 22:35 UTC, oliveirabalsa approved these changes

2020-09-25 04:01 UTC, HenrryEsposito commented
Inserimos junto a essa PR a implementação do dashboard do admin que exibe informações sobre a quantidade de alunos e adesão aos cursos da plataforma, aproveitamos também para corrigir e melhorar alguns detalhes na responsividade dos componentes "PieChart" e "ChartCard" que são utilizados nesse dashboard.

Card Trello: https://trello.com/c/sWGVVi7S/18-150-tela-de-dashboard-admin-m

2020-09-25 21:40 UTC, oliveirabalsa approved these changes

2020-09-26 00:24 UTC, merged