Side, Navigation menus, padronizações e ajustes
NewSchoolApp/newschool-frontend pull request #28
Opened 2019-12-27 06:01 UTC by andrews-felipe

- Ajustes de sintaxe e padronização de informações no <script>
- Navigation-menu
- Side-menu ( Dados do usuário ainda mockados)
- 404 Page
- Custom Routes ( Foi adicionado o [router-extras-module](https://github.com/nuxt-community/router-extras-module) para melhor manipulação das rotas: names, params... etc
- Semântica estrutural das pastas padronizada.

2019-12-27 06:12 UTC, marcios approved these changes

2019-12-27 11:16 UTC, thii777 approved these changes

2019-12-27 12:28 UTC, ErisvaldoCorreia approved these changes

2019-12-27 12:51 UTC, wantero requested changes

2019-12-27 12:51 UTC, wantero commented on components/SideMenu.vue
> +    user: {
@andrews-felipe que tal buscar os dados do usuário do endpoint /api/v1/user/me ?

2019-12-27 13:32 UTC, andrews-felipe commented on components/SideMenu.vue
> +    user: {
pode ser, já está apto pra receber ?

2019-12-27 13:38 UTC, wantero commented on components/SideMenu.vue
> +    user: {
Sim, dá uma olhada no swagger. Sobre a photo no MVP não temos a foto do usuário no Figma e nem no backend.

2019-12-27 14:17 UTC, marcusvcribeiro approved these changes

2019-12-27 15:17 UTC, andrews-felipe commented on components/SideMenu.vue
> +    user: {
foi alinhado que a foto não iria ser colocada nessa MVP, portanto vou adequar o ngx-avatar

2019-12-27 19:56 UTC, filipefelice approved these changes
Nice Andrews! 
Aprovadissima. 👏👌

2019-12-28 04:06 UTC, wantero commented
Precisa de ajuda com o merge?

2019-12-29 02:10 UTC, filipefelice approved these changes
Boa! ✔👏

2019-12-29 02:49 UTC, wantero requested changes

2019-12-29 02:49 UTC, wantero commented on components/SideMenu.vue
> +    user: {
Dados não estão vindo do endpoint /me

2019-12-29 02:49 UTC, wantero commented on components/SideMenu.vue
> +import Avatar from "vue-avatar";
Com a remoção da foto, ainda tem necessidade de usar esse vue-avatar?

2019-12-29 06:35 UTC, andrews-felipe commented on components/SideMenu.vue
> +import Avatar from "vue-avatar";
como alinhado o avatar com sigla permanece hehe

2019-12-29 06:35 UTC, andrews-felipe commented on components/SideMenu.vue
> +    user: {
feito! ( :

2019-12-29 15:44 UTC, wantero requested changes
Recomendações de segurança.

2019-12-29 15:44 UTC, wantero commented on services/http/auth.js
> +          localStorage.setItem("user", JSON.stringify(res.data))
@andrews-felipe não é recomendado armazenar todos os dados do usuário no local storage. Ideal seria armazenar somente o ID e talvez o nome se você precisar se lembrar para o preenchimento de algum form, pois temos dados sensíveis neste objeto. Hoje somente o e-mail, facebook e instagram dele, mas futuramente poderemos ter dados como CPF e outras coisas.

Como o nosso endpoint /me sempre retorna os dados do usuário logado, você nem precisaria armazenar nada em localstorage, ficando mais segura a aplicação.

2019-12-29 15:44 UTC, wantero commented on components/SideMenu.vue
> +        this.user = userStorage;
dá uma olhada no comentário do auth,js. Você precisará buscar os dados novamente do me para pegar os dados do usuário logado.

2019-12-29 19:36 UTC, andrews-felipe commented on services/http/auth.js
> +          localStorage.setItem("user", JSON.stringify(res.data))
Em relação a isso farei o seguinte, vou armazenar apenas o nome do usuário no local_storage e caso a gente precise obter de novo, vou preparar um serviço pra retornar isso sempre que solicitado.

2019-12-29 20:48 UTC, wantero approved these changes

2019-12-29 20:48 UTC, merged

2019-12-29 21:27 UTC, gustavomcastro commented on components/SideMenu.vue
> +    flagdisplayInfoUser: false,
Adicionar camelCase (flagDisplayInfoUser)

2019-12-29 21:27 UTC, gustavomcastro commented on services/http/auth.js
> +          accessToken: `Bearer ${res.data.accessToken}`,
Indico salvar somente o access token, e a concatenação ser realizada diretamente no interceptor.

2019-12-29 21:27 UTC, gustavomcastro commented on services/http/auth.js
> +        localStorage.setItem("auth", JSON.stringify(auth))
Indico salvar os dados de autorização no session storage. Caso o sistema possa ser acessado mais de uma aba utilizando os mesmos dados ok...

Indico separar as keys a serem guardadas no storage utilizando nomes incomuns.

O que é comum utilizado também, é a criação de um service/classe para controlar tudo que acessa os storages, possibilitando assim a reutilização nas implementações de refresh ou outra implementação que tenha que manipular os dados de sessão

`localStorage.setItem("a_Tk", variavelToken)
localStorage.setItem("r_Tk", variavelRefresh)`

2019-12-29 21:27 UTC, gustavomcastro commented on services/http/auth.js
> +
Para facilitar as implementações dos services o que acham de Criamos um interceptor? 

@wantero @andrews-felipe  @raffacabofrio