menu inferior
NewSchoolApp/newschool-frontend pull request #47
Opened 2019-12-30 18:33 UTC by cbarauna

Inclusão do menu inferior

2019-12-30 18:37 UTC, wantero approved these changes

2019-12-30 18:41 UTC, wantero requested changes
@cbarauna Dá uma olhada no comentário no CARD para adequação da fonte e de algumas bordas.

2019-12-30 18:52 UTC, ErisvaldoCorreia approved these changes
Se a expansão indica 100%, não vejo necessidade de usar o prefixo max para o height no v-img

2019-12-31 01:25 UTC, cbarauna commented
> Se a expansão indica 100%, não vejo necessidade de usar o prefixo max para o height no v-img

Nesse caso usuar somente o height 100%?

2019-12-31 04:49 UTC, andrews-felipe commented on pages/quem_somos.vue
>        <v-img :src="require('../assets/projeto-2.jpg')" max-height="100%" class="grey darken-4" />
no último ficou max-height, isso muda algo na tela?
fora isso ta de boas!!

2019-12-31 04:50 UTC, andrews-felipe approved these changes

2019-12-31 11:52 UTC, cbarauna commented on pages/quem_somos.vue
>        <v-img :src="require('../assets/projeto-2.jpg')" max-height="100%" class="grey darken-4" />
Muda nada não. Foi vacilo meu

2020-01-02 01:20 UTC, wantero approved these changes

2020-01-02 01:20 UTC, merged