Inclusão do Rollbar na contribua e ajustes de tamanho
NewSchoolApp/newschool-frontend pull request #52
Opened 2019-12-30 23:28 UTC by oliveirabalsa

https://trello.com/c/t5sEbXYT/54-incluir-rollbar-na-page-contribua

2019-12-30 23:50 UTC, wantero requested changes

2019-12-30 23:50 UTC, wantero commented on pages/public/contribute.vue
> +          id: 3,
pq mudou o id de 1 para 3? Todos ficaram com id 3.

2019-12-30 23:50 UTC, wantero commented on pages/public/contribute.vue
> +          id: 3,
pq mudou o id de 2 para 3? Todos ficaram com id 3.

2019-12-30 23:50 UTC, wantero commented on .vscode/settings.json
> +    "git.ignoreLimitWarning": true
é necessário ignorar os warnings no vscode?

2019-12-30 23:52 UTC, oliveirabalsa commented on .vscode/settings.json
> +    "git.ignoreLimitWarning": true
Não, foi feio sem intenção isso, vou remover e dar push novamente

2019-12-30 23:54 UTC, oliveirabalsa commented on pages/public/contribute.vue
> +          id: 3,
Tbm irei corrigir, foram testes que esqueci de arrumar

2019-12-31 00:02 UTC, wantero approved these changes

2019-12-31 00:24 UTC, filipefelice approved these changes
Boa Doutor! Cada vez mais orgulhoso.
Fez até mais que o necessário 👏🏻

2019-12-31 00:29 UTC, merged