(1.14) Fluxo de refresh token
NewSchoolApp/newschool-frontend pull request #75
Opened 2020-01-03 19:48 UTC by guimalonso

Implantação no front-end do fluxo de Refresh Token para as rotas de admin e aluno.

- Alteração no login para salvar tempo de expiração (em milissegundos) no localStorage (junto com os tokens);
- Middleware que verifica se accessToken está expirado, tenta atualizá-lo e faz redirecionamento para o login em caso de falha (refreshToken expirado) - executado apenas ao entrar nas rotas de admin e aluno;
- Mensagem de sessão expirada para o usuário, caso ocorra o redirecionamento para o login.

Obs.: O excesso de alterações no arquivo services/http/auth.js foram devido ao eslint/prettier.

2020-01-03 20:10 UTC, filipefelice approved these changes
Ficou muito bacana @guimalonso.
Para este primeiro momento atende bem, mas depois podemos pensar em algo usando Vuex e setando as páginas restritas nelas mesmo, sem precisar fazer essa condição de parts no middleware.
Parabéns 👏👌✔

2020-01-03 20:28 UTC, andrews-felipe commented
Ótimo, só uma dúvida, eu vi que você criou um método no login, ele já ta fazendo o redirecionamento?

2020-01-03 20:29 UTC, andrews-felipe approved these changes

2020-01-03 20:51 UTC, guimalonso commented
> Ótimo, só uma dúvida, eu vi que você criou um método no login, ele já ta fazendo o redirecionamento?

Não entendi a pergunta, de qual método você está falando?

2020-01-04 18:10 UTC, andrews-felipe commented
> > Ótimo, só uma dúvida, eu vi que você criou um método no login, ele já ta fazendo o redirecionamento?
> 
> Não entendi a pergunta, de qual método você está falando?

é tipo, o usuário entra no sistema e como a rota default é o login, casos ele esteja autenticado ele passa para a home

2020-01-04 18:19 UTC, wantero requested changes

2020-01-04 18:19 UTC, wantero commented on middleware/auth.js
> +  if (pathParts[1] === 'admin' || pathParts[1] === 'aluno') {
não seria admin e student?

2020-01-04 18:35 UTC, andrews-felipe commented on middleware/auth.js
> +  if (pathParts[1] === 'admin' || pathParts[1] === 'aluno') {
é que as rotas estão personalizadas, aqui ele tá verificando qual raiz de rota está sendo acessada usando o route do vue, ou seja, cada fluxo segue assim

- /admin/* rotas de admin
- /aluno/* rotas de studant

2020-01-04 18:41 UTC, wantero commented on middleware/auth.js
> +  if (pathParts[1] === 'admin' || pathParts[1] === 'aluno') {
show.

2020-01-04 18:41 UTC, wantero approved these changes

2020-01-04 18:41 UTC, merged